### ISSUE TITLE
请问该实例有没有考虑过Map资源回收的问题？

### ISSUE THREAD

**Issue by TKaxv-7S** [zw201913/applogin#1]
我认真看了你的code发现Map没有写回收机制，而使用session则不会产生此问题，如果一个用户登陆了而不点退出的话，只要服务器一直开着，两个map里对应用户的值应该都不会销毁，以此反复，会不会造成占用大量资源的情况？

**Comment by zw201913** [comment]
您好，感谢您的codeview，您说的非常对，map没有清楚机制却是会造成资源浪费。
因为这个demo没有使用到数据库，我在service中使用map就是为了省掉数据库这一步，使用map做一个缓存，这样每个人都可以不需要数据库直接就跑起来。
感谢您给出的建议，这个demo主要表达的思想还是在aop切面，service层只是做了一个简单可用的实现。

**Comment by TKaxv-7S** [comment]
我明白你的意思了，还是很感谢你的code！
